### ISSUE TITLE
Could you include some example code?

### ISSUE THREAD

**Issue by ronikobrosly** [v2e4lisp/pdf417-text-mode-decoder#2]
I'm really glad you've been working on this. Could you add a super small script where you decode an example barcode? Like this perhaps: https://en.wikipedia.org/wiki/PDF417#/media/File:Better_Sample_PDF417.png

**Comment by v2e4lisp** [comment]
I updated the script and added the wikipedia image to the test dir. Now you can run it like `./pdf417.py test/Better_Sample_PDF417.png` and it will decode the image and print out its text content.

`pdf417.py` depends on PIL or Pillow. Make sure either of these two packages is installed on your machine. I installed Pillow on my machine using pip. `sudo pip install pillow`

**NOTE THAT**
1. The script probably has some bugs in it. Don't use it for any serious work. Find some decent barcode decoder library.
2. I'm NOT maintaining the project and don't have any plan to. I wrote this code about 4 or 5 years ago, and now I can hardly understand how it works.

The instructions below is how I installed dependencies and ran the script. Hope it helps.

```
# install pip. If you have pip installed skip this.
sudo easy_install pip

# install Pillow. If you have Pillow / PIL installed skip this
sudo pip install pillow

# git clone this package
git clone https://github.com/v2e4lisp/pdf417-text-mode-decoder.git

# run it
cd pdf417-text-mode-decoder
./pdf417.py test/Better_Sample_PDF417.png
```

**Comment by ronikobrosly** [comment]
Thanks for your very fast reply, Yan! I completely understand the caveats.
